### ISSUE TITLE
Macfag here, the whole thing isn't working for me

### ISSUE THREAD

**Issue by Reinso** [zmnmxlntr/hg#1]
So I'm on a mac, and I installed this into tampermonkey to host a thread, but, everything doesn't work. The only things that show up are the Draw, Hide, Save, and Deselect all buttons with the three little circles to select, but they don't apparently do anything. The options to change gender and names don't show up, and neither does the option to select candidates. Finally, the Load button doesn't show up on bransteele either. Is this issue because I'm using a mac? 
Edit: Oh, guess it is, I just saw this hasn't been tested on anything that isn't windows. Well I guess I'm fucked then.

**Comment by zmnmxlntr** [comment]
Problem resolved upon user re-installing Chrome.
